# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
env NODE_ENV=production
COPY package.json ./
RUN npm install --production

# Copy source files
COPY . ./

# Expose stdio-based MCP server (no network ports)

# Start the MCP server
CMD ["node", "calculator-server.js"]
